#!/usr/bin/env bash

if [[ "$1" = "" ]]; then
    echo "shed requires a url"
else
    echo "saving webpage"
    # get page title
    article=$(readable $1 -p title | tr -d "[:punct:][:blank:]" | cut -c 1-25)
    echo $article
    # download page
    readable $1 -s style.css -o ~/shed/$article.html --quiet
    echo -e "\nDONE"
fi
