#!/usr/bin/env bash

if [[ "$1" = "" ]]; then
    echo "shed requires a url"
elif [[ "$1" = "list" ]]; then
    for file in ~/shed/*.html; do basename "$file"; done
else
    # get page title
    article=$(readable "$1" -p title    |
            tr "[:upper:]" "[:lower:]"  |
            sed 's/[$&@!?“”’,-]//g'     |
            tr " " "."                  |
            cut -c 1-64                 |
            tr -s ".")
    # download page
    readable "$1" -s style.css -o ~/shed/"$article".html --quiet
fi
